### ISSUE TITLE
Multiple watch break on dispose

### ISSUE THREAD

**Issue by bago** [ZiadJ/knockoutjs-reactor#25]
```
var options = { depth: -1 };
var a = ko.watch(model, options, listener);
var b = ko.watch(model, options, listener2);
a.dispose();
```

listener2 is not called anymore.

I saw that "context" equals "ko" in the internal checks, for both calls.
I thought I could call the 2 watch with different context but I see the code somewhere uses context(returnValue); so context have probably some meaning that I am missing.

Can you document the "context" stuff or explain me how can I have 2 indipendent watchers?
I use knockout-reactor for a custom function in my project, but the same project also uses my undomanager: when I dispose the first watch the undomanager stops working.

**Comment by bago** [comment]
I tried passing an object as "context" and it worked.
---
var options = { depth: -1 };
var a = ko.watch(model, options, listener);
var b = ko.watch(model, options, listener2, {});
a.dispose();
----

What is the suggested way to use it? A "string"? an Object? Is it the "right way" to isolate it?
In this case I guess my undomanager should simply pass its own object as context: am I right?

**Comment by ZiadJ** [comment]
Yes, any object would do as context as long as they're not the same. The object being watched becomes the context when none is specified.
