### ISSUE TITLE
Bower Accessible

### ISSUE THREAD

**Issue by AStoker** [ZiadJ/knockoutjs-reactor#27]
It would be nice to have this as a bower module so that we can pull this down directly into our projects. Any plans for this in the future? If not, I could make a pull request to do it.

**Comment by ZiadJ** [comment]
Sure that would be a nice addition. I was planning to do it once I manage to pull it out of the current beta phase but it's pretty robust already.

**Comment by AStoker** [comment]
All you got to do is make a release tag (sounds like you need a mark it as a pre-release?), upload a bower config, and then register it with the bower site. Then, any time you have an update, you simply update the bower.json file to the new version number, and make a new release. http://bower.io/docs/creating-packages/

**Comment by cResults** [comment]
This would benefit our team as well.  There is a [coder that appears to be wrapping knockout-reactor as a bower module](https://github.com/esbenp/knockoutjs-reactor-bower), but I'd rather be dependent upon the original source.

**Comment by jakiestfu** [comment]
Bump!

**Comment by ZiadJ** [comment]
Sorry guys, I'm terribly late on other projects right now and won't find time to catch up with things here until a week or two. Meanwhile I wouldn't mind granting one of you full access to the repository if that can ease things up. Anyone interested?

**Comment by jakiestfu** [comment]
I would be interested in maintaining this under the Diamonds org or
jakiestfu account!

**Comment by ZiadJ** [comment]
Welcome aboard @jakiestfu :)

**Comment by jakiestfu** [comment]
Thanks, @ZiadJ, let me know when the transition will happen. Also, if you could spare a few minutes over the phone/g hangout/skype, that'd be great!

**Comment by ZiadJ** [comment]
My Skype name is ziad.jkhan. Feel free to add me anytime.

**Comment by jakiestfu** [comment]
@ZiadJ What is the license for this?

**Comment by ZiadJ** [comment]
@jakiestfu MIT, the source code header has it.

**Comment by jakiestfu** [comment]
@AStoker @cResults @ZiadJ This is now available via bower
