### ISSUE TITLE
AMD module support

### ISSUE THREAD

**Issue by crashnick16** [ZiadJ/knockoutjs-reactor#31]
I am trying to load this library using requireJS but It keeps failing with "Uncaught ReferenceError: ko is not defined ". 

Any ideas what might cause this?

**Comment by ZiadJ** [comment]
Looks more like knockoutjs was not loaded prior to loading the plugin. You might want to look in that direction first.

**Comment by ZiadJ** [comment]
Fixed in the latest update.
