### ISSUE TITLE
How can we reset it?

### ISSUE THREAD

**Issue by Syltty** [ZiadJ/knockoutjs-reactor#32]
Sorry I'm new to knockout.
I have a view in read mode and an Edit button. When the user clicks it then I display an Edit view, start to watch my viewmodel for change and display a Cancel and a Save button.
If the user click the Cancel button I would like to reset the watching.
How could it be possible?
Thank you!

**Comment by ZiadJ** [comment]
If your viewmodel only gets modified when you press Save you might just wire a method to the Cancel button that sets the text back to that in its viewmodel. If it was set to update as you type however then there's an option ```oldValues```(see source code documentation), which allows you to keep track of older values as well.
