### ISSUE TITLE
Not Compatible with knockout 3.4

### ISSUE THREAD

**Issue by jrsearles** [ZiadJ/knockoutjs-reactor#34]
Knockout 3.4 was just released and this library breaks with the minified version.

**Comment by crashnick16** [comment]
+1

**Comment by ZiadJ** [comment]
Ok, I'll fix it over the week. It's just that I'm super late on some other projects right now. The subscription name under v3.4 was changed so meanwhile you can fix it by adding `<case "3.4.0": subscriptionsField = 'NewFieldName'; break;>` to `<switch (ko.DEBUG || ko.version) { ... }>`. The field name in question can be identified while debugging and it is created right after calling `<.subscribe()>` on any observable. I'd expect it to be a capital letter like before.

**Comment by bago** [comment]
It should be "K". I'll try to make a PR soon
