### ISSUE TITLE
Uncaught Subscriptions field (.G) not defined for observable child 

### ISSUE THREAD

**Issue by sudsy** [ZiadJ/knockoutjs-reactor#36]
Hi There,

I am recieving this exception using your beta version on a regular basis. Have you got any idea what might be causing it? If not, I will dig further into this when I get a chance.

**Comment by bago** [comment]
This may depend on the version of knockout: which version are you using?
reactor should try to look for G when detecting knockout 3.3.0 "non debug".

An error like the one you describe may happen if you built your own version of KO 3.3.0.

**Comment by sudsy** [comment]
We are using a standard build of ko 3.3.0 but I could try an upgrade to
3.4.0.

I noticed that knockoutjs-reactor on bower is different to this repo with
the beta build in the dist folder. Will you be publishing a new build
without beta. I don't want to reference that file if it will break soon.

**Comment by bago** [comment]
I use bower and include reactor using this:
---
    "knockoutjs-reactor": "ZiadJ/knockoutjs-reactor#273d140ce28e7cecf0f573a605d259e22cbfc319", 
----
It works fine with both KO 3.3 and KO 3.4.
