### ISSUE TITLE
"un-watch" functionality...

### ISSUE THREAD

**Issue by jgergenhotmail** [ZiadJ/knockoutjs-reactor#38]
Hello,
I do not see in your documentation the ability to "un-watch" a view model.  Does this automatically occur when ko.cleanNode(...) is called?

Thanks,
Jim

**Comment by ZiadJ** [comment]
You "un-watch" by calling .dispose on the object that's returned from .watch. Sorry, I should have mentioned it in the docs and probably will in the next update.

**Comment by ZiadJ** [comment]
@jgergenhotmail Just call `.dispose()` on the object that's returned by `.watch(...)`. I should have mentioned it in the docs but will make sure it's there in the next update.
