### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bago** [ZiadJ/knockoutjs-reactor#40]
Hi ZiadJ, what about making a new release? It's a long time since the last proper release (1.3.0) and a lot of fixes/changes.

If you need help I can do that if you give me privileges to the project.

**Comment by ZiadJ** [comment]
Sure, I'll grant you the privileges you need over the weekend. I'm just too busy with some other voluntary work right now to make this quick enough.

**Comment by ZiadJ** [comment]
@bago Done!

**Comment by bago** [comment]
I bumped the release number, built it, pushed and did a release on github!
